import { useState } from "react";

import InputField from "../../components/common/InputField";
import SelectField from "../../components/common/SelectField";

function AssetForm() {
  const [formData, setFormData] = useState({
    assetName: "",
    assetTag: "",
    serialNumber: "",
    category: "",
    department: "",
    purchaseDate: "",
    purchaseCost: "",
    vendor: "",
    warrantyExpiry: "",
    status: "",
  });

  const handleChange = (event) => {
    setFormData({
      ...formData,
      [event.target.name]: event.target.value,
    });
  };

  const handleSubmit = (event) => {
    event.preventDefault();

    console.log(formData);

    alert("Asset saved successfully!");
  };

  return (
    <div className="mx-auto max-w-6xl rounded-2xl bg-white p-8 shadow">
      <h1 className="mb-8 text-3xl font-bold">
        Register Asset
      </h1>

      <form
        onSubmit={handleSubmit}
        className="space-y-8"
      >
        {/* Asset Information */}
        <div>
          <h2 className="mb-5 text-xl font-semibold">
            Asset Information
          </h2>

          <div className="grid gap-6 md:grid-cols-2">
            <InputField
              label="Asset Name"
              name="assetName"
              value={formData.assetName}
              onChange={handleChange}
            />

            <InputField
              label="Asset Tag"
              name="assetTag"
              value={formData.assetTag}
              onChange={handleChange}
            />

            <InputField
              label="Serial Number"
              name="serialNumber"
              value={formData.serialNumber}
              onChange={handleChange}
            />

            <SelectField
              label="Category"
              name="category"
              value={formData.category}
              onChange={handleChange}
              options={[
                "Electronics",
                "Furniture",
                "Vehicles",
              ]}
            />

            <SelectField
              label="Department"
              name="department"
              value={formData.department}
              onChange={handleChange}
              options={[
                "Engineering",
                "HR",
                "Finance",
              ]}
            />

            <SelectField
              label="Status"
              name="status"
              value={formData.status}
              onChange={handleChange}
              options={[
                "Available",
                "Allocated",
                "Maintenance",
              ]}
            />
          </div>
        </div>

        {/* Purchase Details */}
        <div>
          <h2 className="mb-5 text-xl font-semibold">
            Purchase Details
          </h2>

          <div className="grid gap-6 md:grid-cols-3">
            <InputField
              label="Purchase Date"
              name="purchaseDate"
              type="date"
              value={formData.purchaseDate}
              onChange={handleChange}
            />

            <InputField
              label="Purchase Cost"
              name="purchaseCost"
              type="number"
              value={formData.purchaseCost}
              onChange={handleChange}
            />

            <InputField
              label="Vendor"
              name="vendor"
              value={formData.vendor}
              onChange={handleChange}
            />
          </div>
        </div>

        {/* Warranty */}
        <div>
          <h2 className="mb-5 text-xl font-semibold">
            Warranty
          </h2>

          <div className="grid gap-6 md:grid-cols-2">
            <InputField
              label="Warranty Expiry"
              name="warrantyExpiry"
              type="date"
              value={formData.warrantyExpiry}
              onChange={handleChange}
            />

            <div className="flex flex-col gap-2">
              <label className="text-sm font-medium text-slate-700">
                Asset Image
              </label>

              <input
                type="file"
                className="rounded-xl border border-slate-300 p-3"
              />
            </div>
          </div>
        </div>

        {/* QR Code Placeholder */}
        <div className="rounded-xl border-2 border-dashed border-slate-300 p-8 text-center">
          <p className="text-gray-500">
            QR Code will be generated by the backend
          </p>
        </div>

        {/* Buttons */}
        <div className="flex justify-end gap-4">
          <button
            type="reset"
            className="rounded-xl border px-6 py-3"
          >
            Reset
          </button>

          <button
            type="submit"
            className="rounded-xl bg-blue-600 px-6 py-3 text-white hover:bg-blue-700"
          >
            Save Asset
          </button>
        </div>
      </form>
    </div>
  );
}

export default AssetForm;